# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      global-development-dependencies:
        dependency-type: development
      global-production-dependencies:
        dependency-type: production

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: monthly
    groups:
      client-development-dependencies:
        dependency-type: development
      client-production-dependencies:
        dependency-type: production

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: monthly
    groups:
      server-development-dependencies:
        dependency-type: development
      server-production-dependencies:
        dependency-type: production
